<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(MSBuildThisFileDirectory)$(MSBuildProjectName).props" Condition="Exists('$(MSBuildThisFileDirectory)$(MSBuildProjectName).props')" />
  <PropertyGroup>
    <ApiAssemblyName Condition="'$(ApiAssemblyName)' == ''">$(AssemblyName).Api</ApiAssemblyName>
    <ApiProjectPath>$(ApiAssemblyName)\$(ApiAssemblyName).csproj</ApiProjectPath>
  </PropertyGroup>
  <PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="$(CoreProduct).Core.Attributes.PackageReferenceAssemblyAttribute">
      <_Parameter1>All</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="$(TestsAssemblyName)" />
  </ItemGroup>
  <PropertyGroup Label="Path">
    <RelativeCurrentPkgFolderPath Condition="'$(RelativeCurrentPkgFolderPath)' == ''">./</RelativeCurrentPkgFolderPath>
    <RelativePkgFolderPath Condition="'$(RelativePkgFolderPath)' == ''">$(RelativeCurrentPkgFolderPath)..</RelativePkgFolderPath>
    <ConfLibPath Condition="'$(ConfLibPath)' == ''">$(RelativePkgFolderPath)/../Lib</ConfLibPath>
  </PropertyGroup>
  <Choose>
    <When Condition="'$(TargetFramework)' == 'net472'">
      <PropertyGroup>
        <CoreLibPath Condition="'$(CoreLibPath)' == ''">$(RelativePkgFolderPath)/../../bin</CoreLibPath>
        <StandalonePackageAssemblyPath Condition="'$(StandalonePackageAssemblyPath)' == ''">Files/Bin</StandalonePackageAssemblyPath>
      </PropertyGroup>
    </When>
    <When Condition="'$(TargetFramework)' == 'netstandard2.0' Or '$(_IsNetCoreApp)' == 'true'">
      <PropertyGroup>
        <CoreLibPath Condition="'$(CoreLibPath)' == ''">$(RelativePkgFolderPath)/../..</CoreLibPath>
        <StandalonePackageAssemblyPath Condition="'$(StandalonePackageAssemblyPath)' == ''">Files/Bin/netstandard</StandalonePackageAssemblyPath>
      </PropertyGroup>
    </When>
  </Choose>
  <PropertyGroup>
    <OutputPath>$(RelativeCurrentPkgFolderPath)$(StandalonePackageAssemblyPath)</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="$(RelativeCurrentPkgFolderPath)Assemblies/**" />
    <Compile Remove="$(RelativeCurrentPkgFolderPath)Data/**" />
    <Compile Remove="$(RelativeCurrentPkgFolderPath)SqlScripts/**" />
    <Compile Remove="$(RelativeCurrentPkgFolderPath)packages/**" />
    <Compile Remove="$(RelativeCurrentPkgFolderPath)Resources/**" />
    <Compile Remove="$(RelativeCurrentPkgFolderPath)Schemas/**" />
    <EmbeddedResource Remove="$(RelativeCurrentPkgFolderPath)Assemblies/**" />
    <EmbeddedResource Remove="$(RelativeCurrentPkgFolderPath)Data/**" />
    <EmbeddedResource Remove="$(RelativeCurrentPkgFolderPath)SqlScripts/**" />
    <EmbeddedResource Remove="$(RelativeCurrentPkgFolderPath)packages/**" />
    <EmbeddedResource Remove="$(RelativeCurrentPkgFolderPath)Resources/**" />
    <EmbeddedResource Remove="$(RelativeCurrentPkgFolderPath)Schemas/**" />
    <None Remove="$(RelativeCurrentPkgFolderPath)Assemblies/**" />
    <None Remove="$(RelativeCurrentPkgFolderPath)Data/**" />
    <None Remove="$(RelativeCurrentPkgFolderPath)SqlScripts/**" />
    <None Remove="$(RelativeCurrentPkgFolderPath)packages/**" />
    <None Remove="$(RelativeCurrentPkgFolderPath)Resources/**" />
    <None Remove="$(RelativeCurrentPkgFolderPath)Schemas/**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="$(RelativeCurrentPkgFolderPath)tests/**" />
    <Compile Remove="$(RelativeCurrentPkgFolderPath)$(ApiAssemblyName)/**" />
    <Compile Remove="$(RelativeCurrentPkgFolderPath)$(TestsAssemblyName)/**" />
    <EmbeddedResource Remove="$(RelativeCurrentPkgFolderPath)tests/**" />
    <EmbeddedResource Remove="$(RelativeCurrentPkgFolderPath)$(ApiAssemblyName)/**" />
    <EmbeddedResource Remove="$(RelativeCurrentPkgFolderPath)$(TestsAssemblyName)/**" />
    <None Remove="$(RelativeCurrentPkgFolderPath)tests/**" />
    <None Remove="$(RelativeCurrentPkgFolderPath)$(ApiAssemblyName)/**" />
    <None Remove="$(RelativeCurrentPkgFolderPath)$(TestsAssemblyName)/**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="$(RelativeCurrentPkgFolderPath)descriptor.json" />
  </ItemGroup>
  <ItemGroup Condition="'$(_IsNetCoreApp)' == 'true'">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup Label="Package Assembly References">
    <Reference Include="$(RelativeCurrentPkgFolderPath)Autogenerated/Lib/*.dll">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup Label="Package Assembly References">
    <ProjectReference Include="$(ApiProjectPath)" Condition="Exists('$(ApiProjectPath)')">
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>
  <Choose>
    <When Condition="'$(TargetFramework)' == 'net472'">
      <ItemGroup>
        <Reference Include="System.ServiceModel" />
        <Reference Include="System.ServiceModel.Activation" />
        <Reference Include="System.ServiceModel.Web" />
        <Reference Include="System.Web" />
      </ItemGroup>
      <ItemGroup Label="Core References">
        <Reference Include="$(CoreProduct).Reports">
          <HintPath>$(CoreLibPath)/$(CoreProduct).Reports.dll</HintPath>
          <SpecificVersion>False</SpecificVersion>
          <Private>False</Private>
        </Reference>
        <Reference Include="$(CoreProduct).GoogleServices">
          <HintPath>$(CoreLibPath)/$(CoreProduct).GoogleServices.dll</HintPath>
          <SpecificVersion>False</SpecificVersion>
          <Private>False</Private>
        </Reference>
      </ItemGroup>
    </When>
    <When Condition="'$(TargetFramework)' == 'netstandard2.0' Or '$(_IsNetCoreApp)' == 'true'">
      <ItemGroup Label="Core References">
        <Reference Include="$(CoreProduct).Messaging.Common.Standard">
          <HintPath>$(CoreLibPath)/$(CoreProduct).Messaging.Common.Standard.dll</HintPath>
          <SpecificVersion>False</SpecificVersion>
          <Private>False</Private>
        </Reference>
        <Reference Include="$(CoreProduct).ServiceModel.Primitives">
          <HintPath>$(CoreLibPath)/$(CoreProduct).ServiceModel.Primitives.dll</HintPath>
          <SpecificVersion>False</SpecificVersion>
          <Private>False</Private>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
  <!--<ItemGroup Label="Package Lib References">
      <Reference Include="$(RelativeCurrentPkgFolderPath)Files/Lib/*.dll">
        <Private>True</Private>
      </Reference>
    </ItemGroup>-->
  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
  </ItemGroup>
  <ItemGroup Label="Core References">
    <Reference Include="$(CoreProduct).Core">
      <HintPath>$(CoreLibPath)/$(CoreProduct).Core.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
      <Private>False</Private>
    </Reference>
    <Reference Include="$(CoreProduct).Core.ServiceModelContract">
      <HintPath>$(CoreLibPath)/$(CoreProduct).Core.ServiceModelContract.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
      <Private>False</Private>
    </Reference>
    <Reference Include="$(CoreProduct).Web.Common">
      <HintPath>$(CoreLibPath)/$(CoreProduct).Web.Common.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
      <Private>False</Private>
    </Reference>
    <Reference Include="$(CoreProduct).ServiceBus">
      <HintPath>$(CoreLibPath)/$(CoreProduct).ServiceBus.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup Label="3-rd party references">
    <Reference Include="BPMStudio.Messaging.MessageBus">
      <HintPath>$(CoreLibPath)/BPMStudio.Messaging.MessageBus.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup Label="Newtonsoft References">
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(CoreLibPath)/Newtonsoft.Json.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup Label="Logging References">
    <Reference Include="Common.Logging">
      <HintPath>$(CoreLibPath)/Common.Logging.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
      <Private>False</Private>
    </Reference>
    <Reference Include="Common.Logging.Core">
      <HintPath>$(CoreLibPath)/Common.Logging.Core.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(Configuration)' == 'Debug' AND '$(RecycleAppPoolName)' != ''">
    <Exec Command="%25windir%25\system32\inetsrv\appcmd recycle apppool $(RecycleAppPoolName)" />
  </Target>
  <Import Project="$(MSBuildThisFileDirectory)$(MSBuildProjectName).targets" Condition="Exists('$(MSBuildThisFileDirectory)$(MSBuildProjectName).targets')" />
</Project>