<Project>
  <PropertyGroup>
    <RootProject>$([System.Text.RegularExpressions.Regex]::Replace($(AssemblyName), '\.Api$', ''))</RootProject>
    <ApiAssemblyUId>bc59c379-50cc-4d88-9725-bf895aa952a4</ApiAssemblyUId>
    <NoWarn>$(NoWarn);RT0001</NoWarn>
  </PropertyGroup>
  <Import Project="../$(RootProject).props" Condition="Exists('../$(RootProject).props')" />
</Project>
