<Project>
  <Import Project="$(MSBuildThisFileDirectory)CI.targets" Condition="Exists('$(MSBuildThisFileDirectory)CI.targets')" />
  <Target Name="Project" BeforeTargets="BeforeCompile">
    <Message Importance="High" Text="*********** Project [$(MSBuildProjectFile)] TargetFramework [$(TargetFramework)] CoreTargetFramework [$(CoreTargetFramework)]" />
  </Target>
  <Target Name="Paths" BeforeTargets="BeforeCompile">
    <Message Importance="High" Text="*********** CoreLibPath [$([System.IO.Path]::GetFullPath('$(CoreLibPath)'))]" />
    <Message Importance="High" Text="*********** RelativeCurrentPkgFolderPath [$([System.IO.Path]::GetFullPath('$(RelativeCurrentPkgFolderPath)'))]" />
    <Message Importance="High" Text="*********** RelativePkgFolderPath [$([System.IO.Path]::GetFullPath('$(RelativePkgFolderPath)'))]" />
    <Message Importance="High" Text="*********** StandalonePackageAssemblyPath [$([System.IO.Path]::GetFullPath('$(StandalonePackageAssemblyPath)'))]" Condition="'$(StandalonePackageAssemblyPath)' != ''" />
    <Message Importance="High" Text="*********** OutputPath [$([System.IO.Path]::GetFullPath('$(OutputPath)'))]" />
  </Target>
</Project>
